### ISSUE TITLE
404 error for zen of python PEP link

### ISSUE THREAD

**Issue by ttafsir** [simonw/sqlite-tutorial-pycon-2023#3]
I received a 404 error while trying the tutorial:

```sh
>>> zen = urllib.request.urlopen(
...     "https://raw.githubusercontent.com/python/peps/main/pep-0020.txt"
... ).read().decode("utf-8")

<OUTPUT OMITTED>

request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
Looking at the [commit history](https://github.com/python/peps/commits/08d688fdcafc1557bf7fc53573e5c84b31b78b5d/pep-0020.txt?browsing_rename_history=true&new_path=peps/pep-0020.rst&original_branch=main), It appears that the project has renamed the `.txt` files to `.rst` and reorganized the peps a bit. 

The new link for the example is: `https://raw.githubusercontent.com/python/peps/main/peps/pep-0020.rst`

**Comment by simonw** [comment]
Thanks for fixing this.
